# fly.toml app configuration file generated for tbol-calcom on 2024-07-14T18:40:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tbol-cal'
primary_region = 'ewr'

[build]
  dockerfile = './Dockerfile.fly'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
